#!/usr/bin/env node
require('pump')(
  process.stdin,
  require('./')(),
  require('flush-write-stream')(
    function write (chunk, encoding, done) {
      process.stdout.write(chunk, encoding)
      done()
    },
    function flush (done) {
      process.stdout.write('\n')
      done()
    }
  ),
  function (error) {
    if (error) {
      throw error
    }
  }
)
